spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
  session:
    store-type: redis
    redis:
      namespace: "spring:session"
  redis:
    host: localshot
    port: 6379

simple:
  oauth2:
    clientId: myApp
    clientSecret: pass


logging:
  level:
    root: debug