POST http://localhost:8080/
Content-Type: application/json

{
  "username": "dongchul",
  "password" : "password"
}

###

GET http://localhost:8080
Accept: application/json

###

POST http://localhost:8080/oauth/token
Authorization: Basic bXlBcHA6cGFzcw
Content-Type: application/x-www-form-urlencoded

grant_type=password&username=dongchul&password=password

###